displayName=Loot Finder
author=AustoneG
description=Filter loot in your bank from the Loot Tracker plugin
tags=bank,loot,tags,favorites
version=0.2.0
plugins=com.lootfinder.LootFinderPlugin
build=standard
